apiVersion: apps/v1
kind: Deployment
metadata:
  name: "webserver"
  labels:
    app: "webserver"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "webserver"
  template:
    metadata:
      labels:
        app: "webserver"
    spec:
      containers:
      - name: webserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80